# Generated by Django 4.1.1 on 2022-10-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizid', models.AutoField(primary_key=True, serialize=False)),
                ('subjectname', models.CharField(max_length=50)),
                ('question1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('question3', models.CharField(max_length=50)),
                ('question4', models.CharField(max_length=50)),
                ('question5', models.CharField(max_length=50)),
                ('correctanswer1', models.CharField(max_length=50)),
                ('correctanswer2', models.CharField(max_length=50)),
                ('correctanswer3', models.CharField(max_length=50)),
                ('correctanswer4', models.CharField(max_length=50)),
                ('correctanswer5', models.CharField(max_length=50)),
                ('eqpoints1', models.CharField(max_length=50)),
                ('eqpoints2', models.CharField(max_length=50)),
                ('eqpoints3', models.CharField(max_length=50)),
                ('eqpoints4', models.CharField(max_length=50)),
                ('eqpoints5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='createQuiz.user')),
                ('nickname', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
            ],
            bases=('createQuiz.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='createQuiz.user')),
                ('degree', models.CharField(max_length=50)),
            ],
            bases=('createQuiz.user',),
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentanswer1', models.CharField(max_length=50)),
                ('studentanswer2', models.CharField(max_length=50)),
                ('studentanswer3', models.CharField(max_length=50)),
                ('studentanswer4', models.CharField(max_length=50)),
                ('studentanswer5', models.CharField(max_length=50)),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createQuiz.quiz')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createQuiz.student')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentscore', models.IntegerField(default=0)),
                ('cAns1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cAns1', to='createQuiz.quiz')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createQuiz.quiz')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createQuiz.student')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createQuiz.teacher'),
        ),
    ]
