# Generated by Django 4.1.1 on 2022-10-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nickname',
        ),
    ]
