# Generated by Django 4.1.1 on 2022-10-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizResults',
            new_name='QuizResult',
        ),
        migrations.RenameModel(
            old_name='StudentAnswers',
            new_name='StudentAnswer',
        ),
    ]
