# Generated by Django 4.1.2 on 2022-10-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='quizid',
        ),
    ]
