# Generated by Django 4.1 on 2022-10-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0002_rename_quizresults_quizresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='cAns1',
        ),
    ]
