# Generated by Django 4.1.1 on 2022-10-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0002_remove_student_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createQuiz.student'),
        ),
    ]
